/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISVGRenderer,
  ISVGRendererInterface,
} from "../../../../../nouns-contracts/NounsDescriptorV2/contracts/interfaces/ISVGRenderer";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "bytes",
                name: "image",
                type: "bytes",
              },
              {
                internalType: "bytes",
                name: "palette",
                type: "bytes",
              },
            ],
            internalType: "struct ISVGRenderer.Part[]",
            name: "parts",
            type: "tuple[]",
          },
          {
            internalType: "string",
            name: "background",
            type: "string",
          },
        ],
        internalType: "struct ISVGRenderer.SVGParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "generateSVG",
    outputs: [
      {
        internalType: "string",
        name: "svg",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "image",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "palette",
            type: "bytes",
          },
        ],
        internalType: "struct ISVGRenderer.Part",
        name: "part",
        type: "tuple",
      },
    ],
    name: "generateSVGPart",
    outputs: [
      {
        internalType: "string",
        name: "partialSVG",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "image",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "palette",
            type: "bytes",
          },
        ],
        internalType: "struct ISVGRenderer.Part[]",
        name: "parts",
        type: "tuple[]",
      },
    ],
    name: "generateSVGParts",
    outputs: [
      {
        internalType: "string",
        name: "partialSVG",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISVGRenderer__factory {
  static readonly abi = _abi;
  static createInterface(): ISVGRendererInterface {
    return new utils.Interface(_abi) as ISVGRendererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISVGRenderer {
    return new Contract(address, _abi, signerOrProvider) as ISVGRenderer;
  }
}
