/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INomoNounsDescriptor } from "./INomoNounsDescriptor";
export type { INomoNounsSeeder } from "./INomoNounsSeeder";
export type { INomoToNounMapper } from "./INomoToNounMapper";
export type { INounsAuctionHouseExtra } from "./INounsAuctionHouseExtra";
