"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.NomoNounsToken__factory = exports.NomoNounsSeeder__factory = exports.NomoNounsDescriptor__factory = exports.NomoNFTDescriptor__factory = exports.mock = exports.interfaces = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.interfaces = __importStar(require("./interfaces"));
exports.mock = __importStar(require("./mock"));
var NomoNFTDescriptor__factory_1 = require("./NomoNFTDescriptor__factory");
Object.defineProperty(exports, "NomoNFTDescriptor__factory", { enumerable: true, get: function () { return NomoNFTDescriptor__factory_1.NomoNFTDescriptor__factory; } });
var NomoNounsDescriptor__factory_1 = require("./NomoNounsDescriptor__factory");
Object.defineProperty(exports, "NomoNounsDescriptor__factory", { enumerable: true, get: function () { return NomoNounsDescriptor__factory_1.NomoNounsDescriptor__factory; } });
var NomoNounsSeeder__factory_1 = require("./NomoNounsSeeder__factory");
Object.defineProperty(exports, "NomoNounsSeeder__factory", { enumerable: true, get: function () { return NomoNounsSeeder__factory_1.NomoNounsSeeder__factory; } });
var NomoNounsToken__factory_1 = require("./NomoNounsToken__factory");
Object.defineProperty(exports, "NomoNounsToken__factory", { enumerable: true, get: function () { return NomoNounsToken__factory_1.NomoNounsToken__factory; } });
