/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IInflator } from "./IInflator";
export type { INounsArt } from "./INounsArt";
export type { INounsDescriptorMinimal } from "./INounsDescriptorMinimal";
export type { INounsDescriptorV2 } from "./INounsDescriptorV2";
export type { INounsSeeder } from "./INounsSeeder";
export type { ISVGRenderer } from "./ISVGRenderer";
