/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockArt } from "./MockArt";
export type { MockAuctionHouse } from "./MockAuctionHouse";
export type { MockDescriptor } from "./MockDescriptor";
export type { TestAuctionHouse } from "./TestAuctionHouse";
