"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INounsAuctionHouse__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var INounsAuctionHouse__factory_1 = require("./INounsAuctionHouse__factory");
Object.defineProperty(exports, "INounsAuctionHouse__factory", { enumerable: true, get: function () { return INounsAuctionHouse__factory_1.INounsAuctionHouse__factory; } });
