/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAuctionHouse } from "./MockAuctionHouse";
export type { TestAuctionHouse } from "./TestAuctionHouse";
