"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.INomoNounsDescriptor__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "BadPaletteLength",
        type: "error",
    },
    {
        inputs: [],
        name: "EmptyPalette",
        type: "error",
    },
    {
        inputs: [],
        name: "IndexNotFound",
        type: "error",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "contract INounsArt",
                name: "art",
                type: "address",
            },
        ],
        name: "ArtUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "string",
                name: "baseURI",
                type: "string",
            },
        ],
        name: "BaseURIUpdated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "bool",
                name: "enabled",
                type: "bool",
            },
        ],
        name: "DataURIToggled",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "contract ISVGRenderer",
                name: "renderer",
                type: "address",
            },
        ],
        name: "RendererUpdated",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "index",
                type: "uint256",
            },
        ],
        name: "accessories",
        outputs: [
            {
                internalType: "bytes",
                name: "",
                type: "bytes",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "accessoryCount",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "backgroundCount",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "index",
                type: "uint256",
            },
        ],
        name: "backgrounds",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "baseURI",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "index",
                type: "uint256",
            },
        ],
        name: "bodies",
        outputs: [
            {
                internalType: "bytes",
                name: "",
                type: "bytes",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "bodyCount",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                components: [
                    {
                        internalType: "uint40",
                        name: "nounId",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "background",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "body",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "accessory",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "head",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "glasses",
                        type: "uint40",
                    },
                ],
                internalType: "struct INomoNounsSeeder.Seed",
                name: "seed",
                type: "tuple",
            },
        ],
        name: "dataURI",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "uint40",
                        name: "nounId",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "background",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "body",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "accessory",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "head",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "glasses",
                        type: "uint40",
                    },
                ],
                internalType: "struct INomoNounsSeeder.Seed",
                name: "seed",
                type: "tuple",
            },
        ],
        name: "generateSVGImage",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "name",
                type: "string",
            },
            {
                internalType: "string",
                name: "description",
                type: "string",
            },
            {
                components: [
                    {
                        internalType: "uint40",
                        name: "nounId",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "background",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "body",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "accessory",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "head",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "glasses",
                        type: "uint40",
                    },
                ],
                internalType: "struct INomoNounsSeeder.Seed",
                name: "seed",
                type: "tuple",
            },
        ],
        name: "genericDataURI",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "index",
                type: "uint256",
            },
        ],
        name: "glasses",
        outputs: [
            {
                internalType: "bytes",
                name: "",
                type: "bytes",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "glassesCount",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "headCount",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "index",
                type: "uint256",
            },
        ],
        name: "heads",
        outputs: [
            {
                internalType: "bytes",
                name: "",
                type: "bytes",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "isDataURIEnabled",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint8",
                name: "paletteIndex",
                type: "uint8",
            },
        ],
        name: "palettes",
        outputs: [
            {
                internalType: "bytes",
                name: "",
                type: "bytes",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_index",
                type: "uint256",
            },
            {
                internalType: "string",
                name: "_color",
                type: "string",
            },
        ],
        name: "setBackgroundOverride",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "baseURI",
                type: "string",
            },
        ],
        name: "setBaseURI",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "toggleDataURIEnabled",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                components: [
                    {
                        internalType: "uint40",
                        name: "nounId",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "background",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "body",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "accessory",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "head",
                        type: "uint40",
                    },
                    {
                        internalType: "uint40",
                        name: "glasses",
                        type: "uint40",
                    },
                ],
                internalType: "struct INomoNounsSeeder.Seed",
                name: "seed",
                type: "tuple",
            },
        ],
        name: "tokenURI",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_index",
                type: "uint256",
            },
        ],
        name: "unsetBackgroundOverride",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class INomoNounsDescriptor__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.INomoNounsDescriptor__factory = INomoNounsDescriptor__factory;
INomoNounsDescriptor__factory.abi = _abi;
