"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC721AQueryable__factory = exports.ERC721AQueryable__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC721AQueryable__factory_1 = require("./ERC721AQueryable__factory");
Object.defineProperty(exports, "ERC721AQueryable__factory", { enumerable: true, get: function () { return ERC721AQueryable__factory_1.ERC721AQueryable__factory; } });
var IERC721AQueryable__factory_1 = require("./IERC721AQueryable__factory");
Object.defineProperty(exports, "IERC721AQueryable__factory", { enumerable: true, get: function () { return IERC721AQueryable__factory_1.IERC721AQueryable__factory; } });
